apiVersion: v1
kind: ConfigMap
metadata:
  name: authbridge-runtime-config
  namespace: smp-agents
data:
  config.yaml: |
    mode: envoy-sidecar
    inbound:
      issuer: "https://keycloak-keycloak.apps.ocp.v7hjl.sandbox2288.opentlc.com/realms/kagenti"
    outbound:
      keycloak_url: "http://keycloak-service.keycloak.svc:8080"
      keycloak_realm: "kagenti"
      default_policy: "passthrough"
    identity:
      type: "spiffe"
      client_id_file: "/shared/client-id.txt"
      client_secret_file: "/shared/client-secret.txt"
      jwt_svid_path: "/opt/jwt_svid.token"
    bypass:
      inbound_paths:
        - "/.well-known/*"
        - "/healthz"
        - "/readyz"
        - "/livez"
