apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smp-agents

labels:
  - pairs:
      app.kubernetes.io/part-of: smp-agents
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  # Skill Advisor
  - skill-advisor/deployment.yaml
  - skill-advisor/service.yaml
  # Bundle Validator
  - bundle-validator/deployment.yaml
  - bundle-validator/service.yaml
  # KG Q&A
  - kg-qa/deployment.yaml
  - kg-qa/service.yaml
  # Playground
  - playground/deployment.yaml
  - playground/service.yaml
  # Skill Builder
  - skill-builder/deployment.yaml
  - skill-builder/service.yaml
