apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproutes.yaml

patches:
  - path: patches/authbridge-runtime-config-override.yaml

images:
  - name: ghcr.io/rrbanda/smp-agents/skill-advisor
    newTag: sha-b24d4378f1849b6e18ac1980bc116b8c1402be2a
  - name: ghcr.io/rrbanda/smp-agents/bundle-validator
    newTag: sha-b24d4378f1849b6e18ac1980bc116b8c1402be2a
  - name: ghcr.io/rrbanda/smp-agents/kg-qa
    newTag: sha-b24d4378f1849b6e18ac1980bc116b8c1402be2a
  - name: ghcr.io/rrbanda/smp-agents/playground
    newTag: sha-b24d4378f1849b6e18ac1980bc116b8c1402be2a
  - name: ghcr.io/rrbanda/smp-agents/skill-builder
    newTag: sha-b24d4378f1849b6e18ac1980bc116b8c1402be2a
