apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproutes.yaml

patches:
  - path: patches/secret-override.yaml

images:
  - name: ghcr.io/rrbanda/smp-agents/skill-advisor
    newTag: sha-e4a115f6bcf449ae752de98b8b215eb551ed46db
  - name: ghcr.io/rrbanda/smp-agents/bundle-validator
    newTag: sha-e4a115f6bcf449ae752de98b8b215eb551ed46db
  - name: ghcr.io/rrbanda/smp-agents/kg-qa
    newTag: sha-e4a115f6bcf449ae752de98b8b215eb551ed46db
  - name: ghcr.io/rrbanda/smp-agents/playground
    newTag: sha-e4a115f6bcf449ae752de98b8b215eb551ed46db
  - name: ghcr.io/rrbanda/smp-agents/skill-builder
    newTag: sha-e4a115f6bcf449ae752de98b8b215eb551ed46db
