apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproutes.yaml

patches:
  - path: patches/authbridge-runtime-config-override.yaml

images:
  - name: ghcr.io/rrbanda/smp-agents/skill-advisor
    newTag: sha-a0f9b254a9cef4582bbaa13915a72906d08f94a0
  - name: ghcr.io/rrbanda/smp-agents/bundle-validator
    newTag: sha-a0f9b254a9cef4582bbaa13915a72906d08f94a0
  - name: ghcr.io/rrbanda/smp-agents/kg-qa
    newTag: sha-a0f9b254a9cef4582bbaa13915a72906d08f94a0
  - name: ghcr.io/rrbanda/smp-agents/playground
    newTag: sha-a0f9b254a9cef4582bbaa13915a72906d08f94a0
  - name: ghcr.io/rrbanda/smp-agents/skill-builder
    newTag: sha-a0f9b254a9cef4582bbaa13915a72906d08f94a0
